source 'https://github.com/CocoaPods/Specs.git'

target 'Segment-Bugsnag_Example', :exclusive => true do
  pod "Segment-Bugsnag", :path => "../"
end

target 'Segment-Bugsnag_Tests', :exclusive => true do
  pod "Segment-Bugsnag", :path => "../"

  pod 'Specta'
  pod 'Expecta'
end
